// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Cnua5sno7xZP0pzQFctOXpg9SBNSuiM',
    appId: '1:725770823630:web:50d2b02bd5058e47502d9f',
    messagingSenderId: '725770823630',
    projectId: 'riyadh-guide-database-9528e',
    authDomain: 'riyadh-guide-database-9528e.firebaseapp.com',
    storageBucket: 'riyadh-guide-database-9528e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBM7s3ZPW0o7C4YiTJ2T74xf_IWnPvEg',
    appId: '1:725770823630:android:16c44d4c751d0af1502d9f',
    messagingSenderId: '725770823630',
    projectId: 'riyadh-guide-database-9528e',
    storageBucket: 'riyadh-guide-database-9528e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFT6Qw-s4UjFrwMIlliKx5rSYZI3W-A2Y',
    appId: '1:725770823630:ios:9598f566bf156e93502d9f',
    messagingSenderId: '725770823630',
    projectId: 'riyadh-guide-database-9528e',
    storageBucket: 'riyadh-guide-database-9528e.appspot.com',
    iosBundleId: 'com.example.riyadhGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFT6Qw-s4UjFrwMIlliKx5rSYZI3W-A2Y',
    appId: '1:725770823630:ios:08fb3a2f1d3b5deb502d9f',
    messagingSenderId: '725770823630',
    projectId: 'riyadh-guide-database-9528e',
    storageBucket: 'riyadh-guide-database-9528e.appspot.com',
    iosBundleId: 'com.example.riyadhGuide.RunnerTests',
  );
}
